import type { TaxReturn } from "./types";

export const mockReturns: TaxReturn[] = [
  {
    id: "return-01",
    clientId: "client-01",
    taxYear: 2025,
    status: "pending-review",
    dueDate: "2026-04-15",
    assignedCPA: "Sarah Kim",
    completenessPercent: 92,
    flagCount: 2,
  },
  {
    id: "return-02",
    clientId: "client-02",
    taxYear: 2025,
    status: "in-progress",
    dueDate: "2026-03-15",
    assignedCPA: "Sarah Kim",
    completenessPercent: 68,
    flagCount: 1,
  },
  {
    id: "return-03",
    clientId: "client-03",
    taxYear: 2025,
    status: "in-progress",
    dueDate: "2026-07-25",
    assignedCPA: "Marcus Delgado",
    completenessPercent: 45,
    flagCount: 0,
  },
  {
    id: "return-04",
    clientId: "client-04",
    taxYear: 2025,
    status: "not-started",
    dueDate: "2026-03-15",
    assignedCPA: "Marcus Delgado",
    completenessPercent: 12,
    flagCount: 0,
  },
  {
    id: "return-05",
    clientId: "client-05",
    taxYear: 2025,
    status: "ready-to-file",
    dueDate: "2026-07-22",
    assignedCPA: "Sarah Kim",
    completenessPercent: 100,
    flagCount: 0,
  },
  {
    id: "return-06",
    clientId: "client-06",
    taxYear: 2025,
    status: "pending-review",
    dueDate: "2026-10-15",
    assignedCPA: "Marcus Delgado",
    completenessPercent: 88,
    flagCount: 1,
  },
  {
    id: "return-07",
    clientId: "client-01",
    taxYear: 2024,
    status: "filed",
    dueDate: "2025-04-15",
    assignedCPA: "Sarah Kim",
    completenessPercent: 100,
    flagCount: 0,
  },
  {
    id: "return-08",
    clientId: "client-05",
    taxYear: 2025,
    status: "in-progress",
    dueDate: "2026-10-15",
    assignedCPA: "Sarah Kim",
    completenessPercent: 55,
    flagCount: 0,
  },
];
