import type { ReturnField } from "./types";

export const mockFields: ReturnField[] = [
  // ── return-01 — Margaret Chen (pending-review, 2 flags) ──
  {
    id: "field-01-wages",
    returnId: "return-01",
    label: "Wages, Salaries, Tips",
    value: "$142,850.00",
    state: "verified",
    sourceDocumentId: "doc-01a",
    sourcePage: 1,
    calculation: "Box 1 wages from W-2: $142,850.00",
    confidence: 98,
  },
  {
    id: "field-01-interest",
    returnId: "return-01",
    label: "Taxable Interest Income",
    value: "$3,240.00",
    state: "ai-generated",
    sourceDocumentId: "doc-01b",
    sourcePage: 1,
    calculation: "Box 1 interest from 1099-INT: $3,240.00",
    confidence: 94,
  },
  {
    id: "field-01-mortgage",
    returnId: "return-01",
    label: "Home Mortgage Interest",
    value: "$18,720.00",
    state: "needs-approval",
    sourceDocumentId: "doc-01c",
    sourcePage: 1,
    calculation: "Box 1 mortgage interest: $18,720.00",
    confidence: 72,
  },
  {
    id: "field-01-std-ded",
    returnId: "return-01",
    label: "Standard Deduction",
    value: "$15,000.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "2025 single filer standard deduction",
  },
  {
    id: "field-01-withholding",
    returnId: "return-01",
    label: "Federal Income Tax Withheld",
    value: "$28,410.00",
    state: "verified",
    sourceDocumentId: "doc-01a",
    sourcePage: 1,
    calculation: "Box 2 federal withholding from W-2: $28,410.00",
    confidence: 99,
  },
  {
    id: "field-01-charity",
    returnId: "return-01",
    label: "Charitable Contributions",
    value: "$8,500.00",
    state: "editable",
    sourceDocumentId: null,
    sourcePage: null,
    confidence: 61,
  },
  {
    id: "field-01-agi",
    returnId: "return-01",
    label: "Adjusted Gross Income",
    value: "$146,090.00",
    state: "ai-generated",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "Wages ($142,850) + Interest ($3,240) = $146,090",
    confidence: 91,
  },

  // ── return-02 — Riverstone Consulting LLC ──
  {
    id: "field-02-gross",
    returnId: "return-02",
    label: "Gross Receipts",
    value: "$487,320.00",
    state: "verified",
    sourceDocumentId: "doc-02b",
    sourcePage: 1,
    calculation: "Sum of 1099-NEC amounts: $312,100 + $98,450 + $76,770",
    confidence: 96,
  },
  {
    id: "field-02-cogs",
    returnId: "return-02",
    label: "Cost of Goods Sold",
    value: "$42,180.00",
    state: "editable",
    sourceDocumentId: "doc-02a",
    sourcePage: 2,
    calculation: "P&L line 12 — Cost of services",
  },
  {
    id: "field-02-rent",
    returnId: "return-02",
    label: "Office Rent Expense",
    value: "$36,000.00",
    state: "verified",
    sourceDocumentId: "doc-02c",
    sourcePage: 3,
    calculation: "$3,000/mo × 12 months",
    confidence: 97,
  },
  {
    id: "field-02-meals",
    returnId: "return-02",
    label: "Meals & Entertainment (50%)",
    value: "$6,840.00",
    state: "needs-approval",
    sourceDocumentId: "doc-02c",
    sourcePage: 7,
    calculation: "Total meals $13,680 × 50% deductible = $6,840",
    confidence: 68,
  },
  {
    id: "field-02-net",
    returnId: "return-02",
    label: "Net Business Income",
    value: "$198,450.00",
    state: "ai-generated",
    sourceDocumentId: "doc-02a",
    sourcePage: 1,
    calculation: "Gross ($487,320) − COGS ($42,180) − Expenses ($246,690)",
    confidence: 85,
  },
  {
    id: "field-02-qbi",
    returnId: "return-02",
    label: "Qualified Business Income Deduction",
    value: "$39,690.00",
    state: "ai-generated",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "Net income ($198,450) × 20% QBI = $39,690",
    confidence: 78,
  },

  // ── return-03 — James & Priya Okonkwo ──
  {
    id: "field-03-wages-j",
    returnId: "return-03",
    label: "Wages — James Okonkwo",
    value: "$98,400.00",
    state: "verified",
    sourceDocumentId: "doc-03a",
    sourcePage: 1,
    calculation: "Box 1 wages from Cascade Health W-2",
    confidence: 99,
  },
  {
    id: "field-03-wages-p",
    returnId: "return-03",
    label: "Wages — Priya Okonkwo",
    value: "$76,200.00",
    state: "verified",
    sourceDocumentId: "doc-03b",
    sourcePage: 1,
    calculation: "Box 1 wages from Meridian Design W-2",
    confidence: 99,
  },
  {
    id: "field-03-dividends",
    returnId: "return-03",
    label: "Ordinary Dividends",
    value: "$4,875.00",
    state: "ai-generated",
    sourceDocumentId: "doc-03c",
    sourcePage: 1,
    calculation: "Box 1a ordinary dividends from 1099-DIV",
    confidence: 93,
  },
  {
    id: "field-03-qualified",
    returnId: "return-03",
    label: "Qualified Dividends",
    value: "$4,210.00",
    state: "ai-generated",
    sourceDocumentId: "doc-03c",
    sourcePage: 1,
    calculation: "Box 1b qualified dividends from 1099-DIV",
    confidence: 93,
  },
  {
    id: "field-03-std-ded",
    returnId: "return-03",
    label: "Standard Deduction (MFJ)",
    value: "$30,000.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "2025 married filing jointly standard deduction",
  },
  {
    id: "field-03-child",
    returnId: "return-03",
    label: "Child Tax Credit",
    value: "$4,000.00",
    state: "editable",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "$2,000 × 2 qualifying children",
  },
  {
    id: "field-03-agi",
    returnId: "return-03",
    label: "Adjusted Gross Income",
    value: "$179,475.00",
    state: "needs-approval",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "Combined wages ($174,600) + Dividends ($4,875)",
    confidence: 88,
  },

  // ── return-04 — Harborview Dental Group ──
  {
    id: "field-04-partnership",
    returnId: "return-04",
    label: "Ordinary Business Income (K-1)",
    value: "$312,000.00",
    state: "ai-generated",
    sourceDocumentId: "doc-04a",
    sourcePage: 1,
    calculation: "Box 1 ordinary business income from K-1",
    confidence: 82,
  },
  {
    id: "field-04-payroll",
    returnId: "return-04",
    label: "Officer Compensation",
    value: "$185,000.00",
    state: "editable",
    sourceDocumentId: "doc-04b",
    sourcePage: 1,
    calculation: "Total officer W-2 wages from payroll summary",
  },
  {
    id: "field-04-guaranteed",
    returnId: "return-04",
    label: "Guaranteed Payments",
    value: "$60,000.00",
    state: "needs-approval",
    sourceDocumentId: "doc-04a",
    sourcePage: 2,
    calculation: "Box 4 guaranteed payments to partners",
    confidence: 70,
  },
  {
    id: "field-04-depreciation",
    returnId: "return-04",
    label: "Section 179 Deduction",
    value: "$24,500.00",
    state: "editable",
    sourceDocumentId: null,
    sourcePage: null,
  },
  {
    id: "field-04-health",
    returnId: "return-04",
    label: "Self-Employed Health Insurance",
    value: "$18,720.00",
    state: "ai-generated",
    sourceDocumentId: "doc-04b",
    sourcePage: 4,
    calculation: "Annual premiums for partners: $1,560 × 12",
    confidence: 75,
  },

  // ── return-05 — Elena Vasquez (ready-to-file) ──
  {
    id: "field-05-wages",
    returnId: "return-05",
    label: "Wages, Salaries, Tips",
    value: "$165,000.00",
    state: "locked",
    sourceDocumentId: "doc-05a",
    sourcePage: 1,
    calculation: "Box 1 wages from Summit Legal W-2",
    confidence: 99,
  },
  {
    id: "field-05-interest",
    returnId: "return-05",
    label: "Taxable Interest Income",
    value: "$1,125.00",
    state: "locked",
    sourceDocumentId: "doc-05b",
    sourcePage: 1,
    calculation: "Box 1 interest from Chase 1099-INT",
    confidence: 99,
  },
  {
    id: "field-05-charity",
    returnId: "return-05",
    label: "Charitable Contributions",
    value: "$6,200.00",
    state: "verified",
    sourceDocumentId: "doc-05c",
    sourcePage: 1,
    calculation: "Sum of itemized receipts: $2,000 + $3,000 + $1,200",
    confidence: 95,
  },
  {
    id: "field-05-std-ded",
    returnId: "return-05",
    label: "Standard Deduction",
    value: "$15,000.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "2025 single filer standard deduction",
  },
  {
    id: "field-05-withholding",
    returnId: "return-05",
    label: "Federal Income Tax Withheld",
    value: "$34,800.00",
    state: "locked",
    sourceDocumentId: "doc-05a",
    sourcePage: 1,
    calculation: "Box 2 federal withholding from W-2",
    confidence: 99,
  },
  {
    id: "field-05-refund",
    returnId: "return-05",
    label: "Estimated Refund",
    value: "$2,140.00",
    state: "verified",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "Withholding ($34,800) − Tax liability ($32,660)",
    confidence: 97,
  },

  // ── return-06 — Northwind Logistics Inc. ──
  {
    id: "field-06-revenue",
    returnId: "return-06",
    label: "Gross Receipts or Sales",
    value: "$2,845,000.00",
    state: "verified",
    sourceDocumentId: "doc-06a",
    sourcePage: 1,
    calculation: "Trial balance — Account 4000 Gross Sales",
    confidence: 98,
  },
  {
    id: "field-06-depreciation",
    returnId: "return-06",
    label: "Depreciation Deduction",
    value: "$187,400.00",
    state: "needs-approval",
    sourceDocumentId: "doc-06b",
    sourcePage: 1,
    calculation: "MACRS depreciation on fleet + warehouse equipment",
    confidence: 74,
  },
  {
    id: "field-06-fuel",
    returnId: "return-06",
    label: "Fuel & Fleet Expense",
    value: "$312,600.00",
    state: "ai-generated",
    sourceDocumentId: "doc-06c",
    sourcePage: 1,
    calculation: "Sum of monthly fleet fuel invoices: $26,050 avg × 12",
    confidence: 89,
  },
  {
    id: "field-06-salaries",
    returnId: "return-06",
    label: "Salaries and Wages",
    value: "$890,200.00",
    state: "verified",
    sourceDocumentId: "doc-06a",
    sourcePage: 3,
    calculation: "Trial balance — Account 6100 Payroll Expense",
    confidence: 97,
  },
  {
    id: "field-06-taxable",
    returnId: "return-06",
    label: "Taxable Income",
    value: "$412,800.00",
    state: "ai-generated",
    sourceDocumentId: "doc-06a",
    sourcePage: 10,
    calculation: "Gross ($2,845,000) − Deductions ($2,432,200)",
    confidence: 86,
  },
  {
    id: "field-06-tax",
    returnId: "return-06",
    label: "Corporate Tax Liability",
    value: "$86,688.00",
    state: "editable",
    sourceDocumentId: null,
    sourcePage: null,
    calculation: "Taxable income ($412,800) × 21% corporate rate",
    confidence: 90,
  },

  // ── return-07 — Margaret Chen 2024 (filed) ──
  {
    id: "field-07-wages",
    returnId: "return-07",
    label: "Wages, Salaries, Tips",
    value: "$128,400.00",
    state: "locked",
    sourceDocumentId: "doc-07a",
    sourcePage: 1,
    calculation: "Box 1 wages from 2024 W-2",
    confidence: 99,
  },
  {
    id: "field-07-mortgage",
    returnId: "return-07",
    label: "Home Mortgage Interest",
    value: "$13,400.00",
    state: "locked",
    sourceDocumentId: "doc-07b",
    sourcePage: 1,
    calculation: "Box 1 mortgage interest from 2024 Form 1098",
    confidence: 99,
  },
  {
    id: "field-07-agi",
    returnId: "return-07",
    label: "Adjusted Gross Income",
    value: "$131,200.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
  },
  {
    id: "field-07-tax",
    returnId: "return-07",
    label: "Total Tax",
    value: "$22,180.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
  },
  {
    id: "field-07-refund",
    returnId: "return-07",
    label: "Refund Amount",
    value: "$1,840.00",
    state: "locked",
    sourceDocumentId: null,
    sourcePage: null,
  },

  // ── return-08 — Elena Vasquez (extension / investments) ──
  {
    id: "field-08-proceeds",
    returnId: "return-08",
    label: "Proceeds from Broker Transactions",
    value: "$84,320.00",
    state: "ai-generated",
    sourceDocumentId: "doc-08a",
    sourcePage: 1,
    calculation: "Sum of Form 1099-B Box 1d proceeds",
    confidence: 91,
  },
  {
    id: "field-08-cost-basis",
    returnId: "return-08",
    label: "Cost Basis",
    value: "$71,850.00",
    state: "ai-generated",
    sourceDocumentId: "doc-08a",
    sourcePage: 2,
    calculation: "Sum of Form 1099-B Box 1e cost basis",
    confidence: 88,
  },
  {
    id: "field-08-st-gain",
    returnId: "return-08",
    label: "Short-Term Capital Gain",
    value: "$4,210.00",
    state: "needs-approval",
    sourceDocumentId: "doc-08a",
    sourcePage: 3,
    calculation: "Short-term proceeds − short-term basis",
    confidence: 79,
  },
  {
    id: "field-08-lt-gain",
    returnId: "return-08",
    label: "Long-Term Capital Gain",
    value: "$8,260.00",
    state: "editable",
    sourceDocumentId: "doc-08a",
    sourcePage: 5,
    calculation: "Long-term proceeds − long-term basis",
  },
  {
    id: "field-08-crypto",
    returnId: "return-08",
    label: "Digital Asset Gains",
    value: "$3,890.00",
    state: "ai-generated",
    sourceDocumentId: "doc-08b",
    sourcePage: 1,
    calculation: "Net realized gain from Coinbase export",
    confidence: 65,
  },
  {
    id: "field-08-carryforward",
    returnId: "return-08",
    label: "Capital Loss Carryforward",
    value: "$2,400.00",
    state: "verified",
    sourceDocumentId: "doc-08c",
    sourcePage: 1,
    calculation: "Prior-year unused capital loss carried forward",
    confidence: 96,
  },
];
